### ISSUE TITLE
Creating a user returns password

### ISSUE THREAD

**Issue by Termuellinator** [sametimesameplace/backend#9]
When creating a new user, the response body looks like this:
```
{
  "id": 2,
  "password": "Anna@2023",
  "last_login": null,
  "is_superuser": false,
  "username": "Anna",
  "first_name": "",
  "last_name": "",
  "email": "anna@mailbox.org",
  "is_staff": false,
  "is_active": true,
  "date_joined": "2023-11-04T10:13:15.907168Z",
  "title": null,
  "bio": "",
  "groups": [],
  "user_permissions": []
}
```
I think we should limit that to id, username, email and date_joined?
Maybe @pythondjay can take a look as he created the serializer.

**Comment by Termuellinator** [comment]
Additionally, the password is not hashed in the database. So i guess the serializer should overwrite the create method and use the User.objects.create_user() method as shown here: https://stackoverflow.com/questions/16857450/how-to-register-users-in-django-rest-framework (not the accepted answer, but the most upvoted one. just using objects.create() won't hash the password).

**Comment by pythondjay** [comment]
Hello, I've modified the serializer as requested. I've tested it and checked the database too. The password's I entered during testing are not the ones being shown in the database, so it does appear that the passwords being entered are now being hashed. I've also limited the view to id, username, email and date_joined instead of all the fields being shown.

**Comment by Termuellinator** [comment]
solved in https://github.com/sametimesameplace/backend/pull/11
